name: validate PR

on:
  pull_request:
    paths:
      - 'memes/**'
      - 'scripts/validate.ts'
      - 'scripts/synonyms.ts'
      - '.github/workflows/validate-pr.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile=false
      - name: Validate memes
        run: pnpm validate
